### ISSUE TITLE
Problem with loading commute data

### ISSUE THREAD

**Issue by GBarnsley** [chrism0dwk/covid19uk#9] opened 2020-04-08 14:43 UTC
Function load_commute_volume in pydata.py doesn't work correctly.
The sort_index sorts by day not date so it ends up in the wrong order and commute.merge doesn't correctly match several dates.
Adding "commute_raw.index = pd.to_datetime(commute_raw.index, format = '%d/%m/%Y')" just after "commute_raw = pd.read_csv(filename, index_col='date')", changes the index to a datetime format, allowing the sorting and merging to work correctly.

**Comment by chrism0dwk** [comment] 2020-04-09 23:28
@GBarnsley good spot, thanks!  Actually, this was caused by a data update having a different date format.  Format now fixed as ISO %Y-%m-%d.  Will Pandas barf if another date format is offered, I wonder?

**Comment by GBarnsley** [comment] 2020-04-10 09:27
Yeah it will break if the day, month, year order changes

**Comment by chrism0dwk** [comment] 2020-04-10 12:01
Good!  We'll then know the format has changed.

**Closed as completed by chrism0dwk** 2020-04-10 12:01 UTC
